import Header from "@/components/template/Header/Header";
import "@/styles/globals.css";
import "bootstrap/dist/css/bootstrap.css";
import Head from "next/head";
import { Container } from "react-bootstrap";
import Profile from "@/components/template/Profile/Profile";


export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>مصطفی مومنی</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="page-wrapper"></div>
      <Container>
        <Header />
        <div className="main-parent mb-5">
          <Profile />
          <div className="main">
              <Component {...pageProps} />
          </div>
        </div>
      </Container>
    </>
  );
}
